// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"flora/commands"
	"flora/configs"
	"flora/database"
	"flora/handlers"
	"github.com/bwmarrin/discordgo"
)

// Injectors from di.go:

// InitializeApp creates the main application with all its dependencies.
func InitializeApp(cfg *configs.Config) (*App, error) {
	db, err := database.Connect(cfg)
	if err != nil {
		return nil, err
	}
	manager := commands.NewManager()
	eventHandler := handlers.NewEventHandler(db, manager)
	session, err := NewDiscordSession(cfg, eventHandler)
	if err != nil {
		return nil, err
	}
	app := NewApp(session, db)
	return app, nil
}

// di.go:

// App holds the core components of the application.
type App struct {
	Session *discordgo.Session
	DB      *sql.DB
}

// NewApp creates the final App object.
func NewApp(s *discordgo.Session, db *sql.DB) *App {
	return &App{Session: s, DB: db}
}

// NewDiscordSession creates a new Discord session and registers all handlers.
func NewDiscordSession(cfg *configs.Config, eh *handlers.EventHandler) (*discordgo.Session, error) {
	s, err := discordgo.New("Bot " + cfg.DiscordToken)
	if err != nil {
		return nil, err
	}

	s.Identify.Intents |= discordgo.IntentGuildMessages | discordgo.IntentMessageContent | discordgo.IntentGuildMembers

	s.AddHandler(eh.OnReady)
	s.AddHandler(eh.OnInteractionCreate)
	s.AddHandler(eh.OnMessageDelete)
	s.AddHandler(eh.OnMemberAdd)
	s.AddHandler(eh.OnMemberRemove)
	s.AddHandler(eh.OnMemberUpdate)

	return s, nil
}
